<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>14</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ApplicationIcon>Assets/satellite-logo.ico</ApplicationIcon>
    </PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>none</DebugType>
	</PropertyGroup>
    

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <None Include="Custom\**" Condition="Exists('Custom')" CopyToPublishDirectory="PreserveNewest" CopyToOutputDirectory="PreserveNewest" />
        <None Include="appdata.json" Condition="Exists('appdata.json')" CopyToPublishDirectory="PreserveNewest" CopyToOutputDirectory="PreserveNewest" />
        <None Include="appdata.template.json" Condition="!Exists('appdata.json')" TargetPath="appdata.json" CopyToPublishDirectory="PreserveNewest" CopyToOutputDirectory="PreserveNewest" />
        <AvaloniaResource Remove="Service\Web\**" />
        <None Remove="Service\Web\**" />
        <AvaloniaResource Remove="Service\Control\**" />
        <None Remove="Service\Control\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.10" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="11.1.5" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.10" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.10" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.10" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.10">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
        <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
        <PackageReference Include="OpenCvSharp4.Windows" Version="4.11.0.20250507" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.3.8" />
        <PackageReference Include="Semi.Avalonia" Version="11.3.7.3" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.9.5" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="11.3.9.5" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaXaml Remove="Service\Web\**" />
        <AvaloniaXaml Remove="Service\Control\**" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Service\Web\**" />
        <Compile Remove="Service\Control\**" />
        <Compile Remove="ViewModels\Converters\CurrentInstanceConverter.cs" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Service\Web\**" />
        <EmbeddedResource Remove="Service\Control\**" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Remove="Service\Web\**" />
        <AdditionalFiles Remove="Service\Control\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Data\Data.csproj" />
      <ProjectReference Include="..\Server\Server.csproj" />
    </ItemGroup>
</Project>
